import React from 'react';
import { Paper, Grid, BottomNavigation, BottomNavigationAction} from '@mui/material';
import {sidebarConfig} from './SidebarConfig';
import { ButtonOrange } from '../../component/util/buttonOrange';

import imageFamily from '../../images/family.svg';
const HomePage = () => {

  return (
    <>
      
      <section style={{maxWidth:"400px",padding: "20px", margin: "auto", backgroundColor:'rgba(0, 0, 0, 0.5)'}}  >
      <img src={imageFamily} alt="imageFamily" />
          {sidebarConfig.map((navigation) => (
            <ButtonOrange key={navigation.title} sx={{width: '100%'}}>
              <Grid item sm={1}>
                {navigation.icon} 
                </Grid>
                <Grid item  sm={8}>
               <h2>{navigation.title} </h2>
               </Grid>
            </ButtonOrange>
          ))}


      </section>
      <Paper sx={{ position: 'fixed', bottom: 0, left: 0, right: 0 }} >
        <BottomNavigation
          sx={{ backgroundColor: '#331A3F' }}
          showLabels
      
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          {sidebarConfig.map((navigation) => (
            <BottomNavigationAction key={navigation.title} sx={{ color: "#fff" }} icon={navigation.icon} label={navigation.title} >
            </BottomNavigationAction>
          ))}
        </BottomNavigation>
      </Paper>

    </>
  );
};
export default HomePage;



// import * as React from 'react';
// import Box from '@mui/material/Box';
// import CssBaseline from '@mui/material/CssBaseline';
// import { BottomNavigation, BottomNavigationAction } from '@mui/material';
// import sidebarConfig from './SidebarConfig';
// import { ButtonOrange } from '../../component/util/buttonOrange';
// import Paper from '@mui/material/Paper';
// import List from '@mui/material/List';
// import ListItem from '@mui/material/ListItem';
// import ListItemAvatar from '@mui/material/ListItemAvatar';
// import ListItemText from '@mui/material/ListItemText';
// import Avatar from '@mui/material/Avatar';

// function refreshMessages() {
//   const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max));

//   return Array.from(new Array(50)).map(
//     () => messageExamples[getRandomInt(messageExamples.length)],
//   );
// }

// export default function HomePage() {
//   const [value, setValue] = React.useState(0);
//   const ref = React.useRef(null);
//   const [messages, setMessages] = React.useState(() => refreshMessages());

//   React.useEffect(() => {
//     ref.current.ownerDocument.body.scrollTop = 0;
//     setMessages(refreshMessages());
//   }, [value, setMessages]);

//   return (
//     <Box sx={{ pb: 7 }} ref={ref}>
//       <CssBaseline />
//       <List>
//         {messages.map(({ primary, secondary, person }, index) => (
//           <ListItem button key={index + person}>
//             <ListItemAvatar>
//               <Avatar alt="Profile Picture" src={person} />
//             </ListItemAvatar>
//             <ListItemText primary={primary} secondary={secondary} />
//           </ListItem>
//         ))}
//       </List>

//     </Box>
//   );
// }

// const messageExamples = [
//   {
//     primary: 'Brunch this week?',
//     secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     primary: 'Birthday Gift',
//     secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     person: '/static/images/avatar/1.jpg',
//   },
//   {
//     primary: 'Recipe to try',
//     secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
//     person: '/static/images/avatar/2.jpg',
//   },
//   {
//     primary: 'Yes!',
//     secondary: 'I have the tickets to the ReactConf for this year.',
//     person: '/static/images/avatar/3.jpg',
//   },
//   {
//     primary: "Doctor's Appointment",
//     secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
//     person: '/static/images/avatar/4.jpg',
//   },
//   {
//     primary: 'Discussion',
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     primary: 'Summer BBQ',
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: '/static/images/avatar/1.jpg',
//   },
// ];